In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
from mpl_toolkits.axes_grid1 import make_axes_locatable

In [2]:
%matplotlib qt5
%config InlineBackend.figure_format = 'svg'

plt.rcParams['figure.figsize'] = [12, 5]
plt.rcParams['font.size'] = 13
plt.ion()

In [3]:
# [+] 함수 구현
def f(z):
    return np.power(z,2)-1

# 함수 테스트
f(0)

-1

In [4]:
z = [4, 1-0.2j, 1.6]
f(z)

array([15.  +0.j , -0.04-0.4j,  1.56+0.j ])

In [7]:
z = np.linspace(-10,10,21)
z

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [28]:
# [+] np.linspace()를 이용하여 x축, y축 값 집합을 생성
x, y = np.meshgrid(np.linspace(-10,10,20), np.linspace(-10,10,20))

In [29]:
mesh = np.add(np.multiply(y,1j),x)
mesh

array([[-10.        -10.j        ,  -8.94736842-10.j        ,
         -7.89473684-10.j        ,  -6.84210526-10.j        ,
         -5.78947368-10.j        ,  -4.73684211-10.j        ,
         -3.68421053-10.j        ,  -2.63157895-10.j        ,
         -1.57894737-10.j        ,  -0.52631579-10.j        ,
          0.52631579-10.j        ,   1.57894737-10.j        ,
          2.63157895-10.j        ,   3.68421053-10.j        ,
          4.73684211-10.j        ,   5.78947368-10.j        ,
          6.84210526-10.j        ,   7.89473684-10.j        ,
          8.94736842-10.j        ,  10.        -10.j        ],
       [-10.         -8.94736842j,  -8.94736842 -8.94736842j,
         -7.89473684 -8.94736842j,  -6.84210526 -8.94736842j,
         -5.78947368 -8.94736842j,  -4.73684211 -8.94736842j,
         -3.68421053 -8.94736842j,  -2.63157895 -8.94736842j,
         -1.57894737 -8.94736842j,  -0.52631579 -8.94736842j,
          0.52631579 -8.94736842j,   1.57894737 -8.94736842j,
       

In [30]:
output = np.abs((f(mesh)))


In [31]:
diverge_len = np.zeros(mesh.shape)
print(diverge_len.shape)

(20, 20)


In [21]:
output

array([[200.00249998, 181.10770276, 164.22241016, 149.34523762,
        136.47344064, 125.60254774, 116.7261753 , 109.83624174,
        104.92378186, 101.98039027, 101.        , 101.98039027,
        104.92378186, 109.83624174, 116.7261753 , 125.60254774,
        136.47344064, 149.34523762, 164.22241016, 181.10770276,
        200.00249998],
       [180.89776118, 162.00308639, 145.12063947, 130.24976008,
        117.38824473, 106.53168543,  97.67292358,  90.80198236,
         85.90692638,  82.97590012,  82.        ,  82.97590012,
         85.90692638,  90.80198236,  97.67292358, 106.53168543,
        117.38824473, 130.24976008, 145.12063947, 162.00308639,
        180.89776118],
       [163.78339354, 144.88616221, 128.00390619, 113.13708499,
        100.28459503,  89.4427191 ,  80.60397013,  73.75635566,
         68.8839604 ,  65.96969001,  65.        ,  65.96969001,
         68.8839604 ,  73.75635566,  80.60397013,  89.4427191 ,
        100.28459503, 113.13708499, 128.00390619, 144.8861

In [22]:
fig = plt.figure()
ax = plt.axes(projection='3d')

ax.scatter(x, y, output, alpha=0.2)

ax.set_xlabel('Real axis')      # 실수부
ax.set_ylabel('Imaginary axis') # 허수부
ax.set_zlabel('Absolute value') # 함수값의 절대값
ax.set_title('One Iteration: $f(z) = z^2 - 1$');


In [23]:
output = np.abs(f(f(mesh))) # 함수 두 번 반복

ax = plt.axes(projection='3d')

ax.scatter(x, y, output, alpha=0.2)

ax.set_xlabel('Real axis')
ax.set_ylabel('Imaginary axis')
ax.set_zlabel('Absolute value')
ax.set_title('Two Iterations: $ f(z) = z^2 - 1$');

In [24]:
selected_values = np.array([0.4 + 0.4j, 0.41 + 0.4j, 0.4 + 0.41j])
num_iter = 9

outputs = np.zeros(
    (num_iter+1, selected_values.shape[0]),  # 10X3 Zero 배열 생성
    dtype=complex  # 데이터 타입: 복소수
)
outputs[0] = selected_values   # 함수 초기 조건

for i in range(num_iter):
    outputs[i+1] = f(outputs[i])  # 10번 함수 반복하는 동안 각 결과를 저장

fig, axes = plt.subplots(1, selected_values.shape[0], figsize=(16, 6))
axes[1].set_xlabel('Real axis')
axes[0].set_ylabel('Imaginary axis')

for ax, data in zip(axes, outputs.T):
    cycle = ax.scatter(
        data.real,  # 실수부
        data.imag,  # 허수부
        c=range(data.shape[0]), 
        alpha=0.6
    )
    ax.set_title(f'Mapping of iterations on {data[0]}')

fig.colorbar(cycle, ax=axes, location='bottom', label='Iteration');

In [32]:
def divergence_rate(mesh, num_iter=10, radius=2):

    z = mesh.copy()
    # 값 별 반복 횟수를 저장
    diverge_len = np.zeros(mesh.shape)

    # 발산되지 않은 값들에 대해 함수를 반복 적용
    for i in range(num_iter):
        # [+] 1. Boolean 배열  마스크 생성
        conv_mask = np.abs(z) < radius

        # [+] 2. 해당 값들에 대한 diverge_len 값 증가
        diverge_len[conv_mask] += 1

        # [+] 3. 해당 값들에 대해 함수 적용
        z[conv_mask] = f(z[conv_mask])

    return diverge_len

In [33]:
x, y = np.meshgrid(np.linspace(-2, 2, 400), np.linspace(-2, 2, 400))
mesh = x + (1j * y)

output = divergence_rate(mesh)

fig = plt.figure(figsize=(5, 5))
ax = plt.axes()

ax.set_title('$f(z) = z^2-1$')
ax.set_xlabel('Real axis')
ax.set_ylabel('Imaginary axis')

im = ax.imshow(output, extent=[-2, 2, -2, 2])
divider = make_axes_locatable(ax)
cax = divider.append_axes('right', size='5%', pad=0.1)
plt.colorbar(im, cax=cax, label='Number of iterations');