## <strong> 6. Pandas 객체 생성 및 조작 </strong>

```Pandas``` 라이브러리 설치

In [1]:
!pip install pandas

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# 헬프 문서 출력
pd?

In [3]:
# 라이브러리 버전 확인
pd.__version__

'2.1.4'

### Pandas 객체: <strong> Series </strong>

In [2]:
# [+] List 객체에서 Series 객체를 생성
ser = pd.Series([0.25, 0.5, 0.75, 1.0])
ser

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
# Pandas 객체 속성: .values
vals = ser.values
print(type(vals))
vals

<class 'numpy.ndarray'>


array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
# Pandas 객체 속성: .index
ind = ser.index
print(ind)
print(list(ind))

RangeIndex(start=0, stop=4, step=1)
[0, 1, 2, 3]


In [7]:
# [+] 레이블 기반 인덱싱
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(ser)
print(ser['a'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25


In [12]:
list(ser.index)

['a', 'b', 'c', 'd']

### <strong> Dictionary와 Series 객체 </strong>

In [9]:
# Dictionary 객체에서 Series 객체를 생성
population_dict = {
    'California': 38332521,   # 미국 연방주 별 인구
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [10]:
# [+] 레이블 기반 인덱싱: 'California'에서 'New York'까지
population['California': 'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

### Pandas 객체:<strong> DataFrame </strong>

In [11]:
# 미국 연방주 별 면적
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312,
    'Illinois': 149995
}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [12]:
# [+] 'population'과 'area' Series 객체를 포함하는 DataFrame 객체 생성
states = pd.DataFrame({
    'population': population,
    'area': area
})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [14]:
# DataFrame 객체의 인덱스와 컬럼
print("Index: ",states.index)
print("Column: ",states.columns)

Index:  Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Column:  Index(['population', 'area'], dtype='object')


In [15]:
# [+] DataFrame으로부터 Series 객체 접근하기
print(states['area'])

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


#### **NumPy 배열로부터 DataFrame 객체 생성**
+ 예제, 오늘의 운세: 금전운(```money_fortune```), 연애운(```love_fortune```)

In [16]:
# [+] 실수 난수로 이루어진 12X2 크기의 NumPy 배열 생성
arr = np.random.randn(12, 2)
arr

array([[-1.25172217, -0.6323727 ],
       [ 0.13956563,  1.51422093],
       [-1.56507015,  0.78992855],
       [-1.48718448,  0.8122579 ],
       [ 0.32181889,  0.24084744],
       [-0.63897855,  1.59008546],
       [-0.29389602, -1.27975599],
       [ 0.1692275 , -0.80175365],
       [ 0.88344342, -0.39331533],
       [ 0.89723845, -1.47204261],
       [-0.98459605,  0.42869556],
       [-0.98068971, -0.48055663]])

In [17]:
# NumPy 배열로부터 DataFrame 객체 생성
df = pd.DataFrame(
    arr, 
    columns=['money_fortune', 'love_fortune'], 
    index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
)

df

money_fortune  love_fortune
Jan      -1.251722     -0.632373
Feb       0.139566      1.514221
Mar      -1.565070      0.789929
Apr      -1.487184      0.812258
May       0.321819      0.240847
Jun      -0.638979      1.590085
Jul      -0.293896     -1.279756
Aug       0.169227     -0.801754
Sep       0.883443     -0.393315
Oct       0.897238     -1.472043
Nov      -0.984596      0.428696
Dec      -0.980690     -0.480557

### <strong> Series 객체 조작 </strong>

#### Dictionary 스타일 조작

In [19]:
# Series 객체 생성
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print(ser)    
print('a' in ser)   # [+] Key + in 키워드
print(0.25 in ser)  # [+] Value + in 키워드
print(ser.keys)    # [+] 인덱스
print(ser.keys)   # [+] 키 집합
ser['e'] = 1.25     # [+] 값 추가
ser['a'] = 0.125    # [+] 값 수정
print(ser)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
True
False
<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>
<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>
a    0.125
b    0.500
c    0.750
d    1.000
e    1.250
dtype: float64


#### 배열 스타일 조작

In [20]:
print(ser['a':'c'])   # 슬라이싱
print(ser[(ser > 0.3) & (ser < 0.8)])   # 논리 연산
# 팬시 인덱싱
ind = ['a', 'e'] 
print(ser[ind])

a    0.125
b    0.500
c    0.750
dtype: float64
b    0.50
c    0.75
dtype: float64
a    0.125
e    1.250
dtype: float64


#### Pandas 객체 인덱싱
+ 정수 기반 인덱싱(암묵적, implicit)
+ 레이블 기반 인덱싱(명시적, explicit)

In [21]:
# 슬라이싱을 이용한 'a', 'b', 'c' 선택
print(ser[0:3])   # 정수 기반 인덱싱 -> 암묵적
print(ser['a':'c'])     # 레이블 기반 인덱싱 -> 명시적

a    0.125
b    0.500
c    0.750
dtype: float64
a    0.125
b    0.500
c    0.750
dtype: float64


### <strong> DataFrame 객체 조작 </strong>

In [22]:
# 특정 Series 객체 접근
states['area']
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [23]:
# [+] Series 객체 추가 (밀도 = 인구 / 면적)
states['density'] = states['population'] / states['area']
states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

#### 인덱서: ```loc```, ```iloc```

In [24]:
# Series 객체 생성
ser = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
ser

1    a
3    b
5    c
dtype: object

In [25]:
# loc 인덱서 -> 명시적 인덱서
print(ser.loc[1]) 
print(ser.loc[1:3])

a
1    a
3    b
dtype: object


In [26]:
# iloc 인덱서 -> 암묵적 인덱서
print(ser.iloc[1])
print(ser.iloc[1:3])

b
3    b
5    c
dtype: object


In [27]:
# DataFrame 객체 = 2차원 배열
print(states.values, '\n')        # 값들을 얻어오기
print(states.T, '\n')             # 전치행렬
print(states.iloc[:3, :2], '\n')  # 정수 기반 슬라이싱
print(states.loc[: 'Illinois', : 'population'])  # 레이블 기반 슬라이싱

[[3.83325210e+07 4.23967000e+05 9.04139261e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]
 [1.95528600e+07 1.70312000e+05 1.14806121e+02]
 [1.28821350e+07 1.49995000e+05 8.58837628e+01]] 

              California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01   

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297 

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135


In [28]:
# 마스킹 + 팬시 인덱싱
states.loc[states.density > 100, ['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

In [29]:
# 값 수정
states.iloc[0, 2] = 90
states

population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763